name: Build CLI Alpine Minimal
on:
  push:
    paths:
      - cli/alpine-minimal/**
      - .github/workflows/cli-alpine-minimal.yaml
      - .github/workflows/docker-reusable.yaml
  workflow_dispatch:
  schedule:
    - cron: '0 12 1,15 * *'

jobs:
  build-and-deploy-alpine-minimal:
    uses: ./.github/workflows/docker-reusable.yaml
    permissions:
      packages: write
    with: 
      name: cli-alpine-minimal
      path: cli/alpine-minimal
      push: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'push' && github.ref_name == 'main') }}
      qemu: true
    secrets: inherit