name: Build CLI Alpine Basic
on:
  push:
    paths:
      - cli/alpine-basic/**
      - .github/workflows/cli-alpine-basic.yaml
      - .github/workflows/docker-reusable.yaml
  workflow_dispatch:
  schedule:
    - cron: '0 12 1,15 * *'

jobs:
  build-and-deploy-alpine-basic:
    uses: ./.github/workflows/docker-reusable.yaml
    with: 
      name: cli-alpine-basic
      path: cli/alpine-basic
      push: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'push' && github.ref_name == 'main') }}
      qemu: true
    secrets: inherit