name: Build CLI Jenkins Agent
on:
  push:
    paths:
      - cli/jenkins-agent/**
  workflow_dispatch:
  schedule:
    - cron: '0 12 1,15 * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Zowe Artifactory
        uses: docker/login-action@v2
        with:
          registry: zowe.jfrog.io-docker-snapshot.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build & Push
        id:   build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || (github.event_name == 'push' && github.ref_name == 'main') }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/zowe/zowe-sample-dockerfiles-cli-jenkins-agent:latest
            zowe.jfrog.io-docker-snapshot.jfrog.io/zowe-sample-dockerfiles-cli-jenkins-agent:latest
          context: cli/jenkins-agent/.
      
      - name: Image Digest
        run:  echo ${{ steps.build.outputs.digest }}